/* global window, document */
(function () {
  'use strict';
  const fmt = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
  const state = { step: 1, tolerance: 'balanced', horizon: 'medium' };
  const $ = id => document.getElementById(id);
  /** Reads credit form values and updates all result UI elements. */
  function updateCreditScore() { const habits = Object.fromEntries(['utilities', 'mobile', 'upi', 'rent'].map(id => [id, $(id).value])); const result = window.NayiDisha.creditScore.calculate(habits); const tier = window.NayiDisha.creditScore.getTier(result.score); $('score').textContent = result.score; $('gauge').style.setProperty('--score-pct', ((result.score - 300) / 550 * 100).toFixed(1)); $('gauge').style.setProperty('--gauge-color', tier.color); $('score-label').textContent = tier.name; $('score-label').className = `rounded-full px-3 py-1 text-xs font-bold ${tier.classes}`; $('drivers').innerHTML = result.drivers.map(text => `<li class="flex gap-2"><span class="text-mint">●</span><span>${text}</span></li>`).join(''); $('tips').innerHTML = result.tips.map(text => `<li class="flex gap-2"><span>✓</span><span>${text}</span></li>`).join(''); }
  /** Shows the specified profiler step and synchronizes its progress controls. @param {number} step */
  function setStep(step) { state.step = step; document.querySelectorAll('.question').forEach(question => question.classList.toggle('hidden', Number(question.dataset.step) !== step)); document.querySelectorAll('[data-dot]').forEach(dot => dot.classList.toggle('active', Number(dot.dataset.dot) <= step)); $('back').classList.toggle('invisible', step === 1); $('next').textContent = step === 3 ? 'See my investment path' : 'Next question'; }
  /** Renders the portfolio recommendation and projection from current profiler state. */
  function showRecommendation() { const portfolio = window.NayiDisha.investmentEngine.recommend(state.tolerance, state.horizon); $('profile-name').textContent = portfolio.name; $('return-chip').textContent = portfolio.label; $('profile-description').textContent = portfolio.description; $('portfolio-list').innerHTML = portfolio.items.map(([title, description]) => `<div class="rounded-xl bg-white p-3"><p class="text-sm font-bold">${title}</p><p class="mt-1 text-xs leading-5 text-slate-500">${description}</p></div>`).join(''); const growth = window.NayiDisha.investmentEngine.projectGrowth(Number($('monthly').value), portfolio.rate); window.NayiDisha.charts.renderGrowthChart($('growth-chart'), growth.principal, growth.projectedValue); $('profiler').classList.add('hidden'); $('profiler-actions').classList.add('hidden'); $('recommendation').classList.remove('hidden'); }
  /** Registers all DOM listeners after deferred dependencies are available. */
  function init() { $('credit-form').addEventListener('submit', event => { event.preventDefault(); updateCreditScore(); }); updateCreditScore(); $('monthly').addEventListener('input', event => { $('monthly-display').textContent = fmt.format(Number(event.target.value)); }); [['#drop-options', 'tolerance'], ['#horizon-options', 'horizon']].forEach(([selector, key]) => document.querySelectorAll(`${selector} .answer-option`).forEach(button => button.addEventListener('click', () => { document.querySelectorAll(`${selector} .answer-option`).forEach(option => option.classList.remove('selected')); button.classList.add('selected'); state[key] = button.dataset.value; }))); $('back').addEventListener('click', () => setStep(Math.max(1, state.step - 1))); $('next').addEventListener('click', () => state.step < 3 ? setStep(state.step + 1) : showRecommendation()); $('restart').addEventListener('click', () => { $('recommendation').classList.add('hidden'); $('profiler').classList.remove('hidden'); $('profiler-actions').classList.remove('hidden'); setStep(1); }); }
  init();
}());
